package Interfaz;

import java.awt.TexturePaint;
import java.awt.event.TextEvent;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JList;

import Mundo.Contenedora.Mensaje;
import Mundo.dao.AnimeDAO;
import Mundo.dao.EstudioDAO;
import Mundo.dao.GeneroDAO;
import Mundo.db.Conexion;
import Mundo.dto.AnimeIDTO;
import Mundo.dto.EstudioIDTO;
import Mundo.dto.GeneroIDTO;

public class formAnime extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     * @param generos 
     * @param array 
     */
	private static  ArrayList<EstudioIDTO> array;
	private static  ArrayList<GeneroIDTO> generos;
	private static Conexion con;
	private int editar=0;
    public formAnime(java.awt.Frame parent, boolean modal, ArrayList<EstudioIDTO> arr, ArrayList<GeneroIDTO> gene, Conexion c) {
        super(parent, modal);;
        con =c;
        initComponents(arr,gene);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param gene2 
     * @param arr 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(ArrayList<EstudioIDTO> arr, ArrayList<GeneroIDTO> gene2) {

        jLabel1 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textDesc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textfecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboEstudio = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        textMusica = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaGeneros = new javax.swing.JList<>();
        textVer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        String[] estudios = new String[arr.size()];
        for (int i = 0; i < arr.size(); i++) {
     	   estudios[i] = arr.get(i).getNombreEstudio();
        }
        comboEstudio.setModel(new javax.swing.DefaultComboBoxModel<>(estudios));
        

        String[] gene = new String[gene2.size()];
        for (int i = 0; i < gene2.size(); i++) {
        	gene[i] = gene2.get(i).getNombreGenero();
        }
        

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Genero");

        jLabel4.setText("Fecha de publicacion");

        jLabel5.setText("Estudio");

        //comboEstudio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Url musica");

        jLabel7.setText("Url Visualizacion");

        jLabel8.setText("Generos");

        jButton1.setText("Enviar");
 
        listaGeneros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = gene;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaGeneros);
        
        
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(97, 97, 97)
                        .addComponent(textNombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(textfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textVer, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jButton1)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(textMusica, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(comboEstudio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)))
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	formAnime dialog = new formAnime(new javax.swing.JFrame(), true, array, generos,con);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void setInfo(AnimeIDTO an) {

        //jScrollPane1;
        //listaGeneros;
        textDesc.setText(an.getDescripcion());
        //textGenero;
       	textMusica.setText(an.getUrlMusica());;
		textNombre.setText(an.getNombreAnime());;
        textVer.setText(an.getUrlVisualizar());;
        textfecha.setText(an.getFechaPublicacion().toString());
        editar=an.getIdAnime();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Enviar
    	if(editar!=0) {
    		List<String> g =listaGeneros.getSelectedValuesList();
        	
        	Mensaje msj = new Mensaje();
        	msj.setIdAnime(editar);
        	msj.setNombreAnime(textNombre.getText());
        	msj.setDescripcion(textDesc.getText());
        	String[] fecha = textfecha.getText().split("/");
        	Date date = new Date(Integer.parseInt(fecha[2]), Integer.parseInt(fecha[1]), Integer.parseInt(fecha[0]));
        	msj.setFechaPublicacion(date);
        	msj.setUrlVisualizar(textVer.getText());
        	msj.setUrlMusica(textMusica.getText());
        	msj.setEstudio(comboEstudio.getSelectedItem().toString());
        	EstudioDAO est = new EstudioDAO();
        	EstudioIDTO e =est.consultID(con, msj);
        	msj.setIdEstudio(e.getId());
        	
        	AnimeDAO an = new AnimeDAO();
        	an.update(con, msj);
        	for (String ge : g) {
        		msj.setGenero(ge);
    			GeneroDAO gdao = new GeneroDAO();
    			GeneroIDTO gdto = gdao.consultID(con,msj);
    		
    			con.ejecutaConsulta(gdto.manytomany(editar));
    		}
    	} else {
	    	List<String> g =listaGeneros.getSelectedValuesList();
	    	
	    	Mensaje msj = new Mensaje();
	    	msj.setNombreAnime(textNombre.getText());
	    	msj.setDescripcion(textDesc.getText());
	    	String[] fecha = textfecha.getText().split("/");
	    	Date date = new Date(Integer.parseInt(fecha[2]), Integer.parseInt(fecha[1]), Integer.parseInt(fecha[0]));
	    	msj.setFechaPublicacion(date);
	    	msj.setUrlVisualizar(textVer.getText());
	    	msj.setUrlMusica(textMusica.getText());
	    	msj.setEstudio(comboEstudio.getSelectedItem().toString());
	    	EstudioDAO est = new EstudioDAO();
	    	EstudioIDTO e =est.consultID(con, msj);
	    	msj.setIdEstudio(e.getId());
	    	AnimeDAO an = new AnimeDAO();
	    	an.insert(con, msj);
	    	for (String ge : g) {
	    		msj.setGenero(ge);
				GeneroDAO gdao = new GeneroDAO();
				GeneroIDTO gdto = gdao.consultID(con,msj);
				int id_anime=0;
				try {
					id_anime = an.consultID(con,msj);
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				con.ejecutaConsulta(gdto.manytomany(id_anime));
			}
	    	dispose();
    	}
    } 
    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> comboEstudio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaGeneros;
    private javax.swing.JTextField textDesc;
    private javax.swing.JTextField textMusica;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textVer;
    private javax.swing.JTextField textfecha;
    // End of variables declaration                   
}
